# -*- coding: utf-8 -*-
"""Iris_flower_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXSHsM8EMQYhfZPOtwA0JR1BrD9rtZy7
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.datasets import load_iris

# -------------------------------------------------------------
# 1. Page Configuration & Title
# -------------------------------------------------------------
st.set_page_config(page_title="K-Means Clustering: Iris Dataset", layout="wide")
st.title("Exercise for K-Means Tutorial")

# -------------------------------------------------------------
# 2. Data Loading & Preparation
# -------------------------------------------------------------
@st.cache_data
def load_data():
    iris = load_iris()
    # Create the initial dataframe with all features
    df_raw = pd.DataFrame(iris.data, columns=iris.feature_names)
    df_raw['flower'] = iris.target

    # Drop sepal features and target for simplicity as per exercise instructions
    df_filtered = df_raw.drop(['sepal length (cm)', 'sepal width (cm)', 'flower'], axis='columns')
    return df_filtered

df = load_data()

# -------------------------------------------------------------
# 3. Sidebar Layout & Sidebar Controls
# -------------------------------------------------------------
st.sidebar.header("Clustering Parameters")

# Sidebar Toggle for Scaling
use_scaling = st.sidebar.checkbox("Apply MinMaxScaler?", value=False,
                                  help="Scaling normalizes the features to a common range (0-1).")

# Sidebar Slider for dynamic K value selection
k_value = st.sidebar.slider("Select Number of Clusters (K):", min_value=1, max_value=6, value=3)

# -------------------------------------------------------------
# 4. Data Preprocessing (Scaling)
# -------------------------------------------------------------
if use_scaling:
    scaler = MinMaxScaler()
    scaled_features = scaler.fit_transform(df[['petal length (cm)', 'petal width (cm)']])
    df_cluster = pd.DataFrame(scaled_features, columns=['petal length (cm)', 'petal width (cm)'])
    st.sidebar.success("MinMaxScaler Applied!")
else:
    df_cluster = df.copy()

# -------------------------------------------------------------
# 5. K-Means Clustering Construction
# -------------------------------------------------------------
km = KMeans(n_clusters=k_value, random_state=42)
yp = km.fit_predict(df_cluster)
df_cluster['cluster'] = yp

# -------------------------------------------------------------
# 6. Main Dashboard Interface Layout
# -------------------------------------------------------------
col1, col2 = st.columns(2)

with col1:
    st.subheader("Interactive Cluster Plot")

    # Create the scatter plot dynamically based on chosen K
    fig, ax = plt.subplots(figsize=(6, 4.5))
    colors = ['blue', 'green', 'yellow', 'purple', 'orange', 'red']

    for cluster_id in range(k_value):
        cluster_df = df_cluster[df_cluster.cluster == cluster_id]
        ax.scatter(
            cluster_df['petal length (cm)'],
            cluster_df['petal width (cm)'],
            color=colors[cluster_id % len(colors)],
            label=f'Cluster {cluster_id}',
            edgecolors='black',
            alpha=0.7
        )

    # Plot cluster centers if K > 1
    if k_value > 1:
        ax.scatter(
            km.cluster_centers_[:, 0],
            km.cluster_centers_[:, 1],
            color='black',
            marker='X',
            s=150,
            label='Centroids'
        )

    ax.set_xlabel('Petal Length (cm)')
    ax.set_ylabel('Petal Width (cm)')
    ax.set_title(f"Clusters Formed (K={k_value})")
    ax.legend()
    st.pyplot(fig)

with col2:
    st.subheader("Elbow Plot (Optimal K Determination)")

    # Calculate sum of squared errors dynamically based on scaling choice
    sse = []
    k_rng = range(1, 10)
    for k in k_rng:
        km_loop = KMeans(n_clusters=k, random_state=42)
        km_loop.fit(df_cluster[['petal length (cm)', 'petal width (cm)']])
        sse.append(km_loop.inertia_)

    # Build the line chart
    fig_elbow, ax_elbow = plt.subplots(figsize=(6, 4.5))
    ax_elbow.set_xlabel('K')
    ax_elbow.set_ylabel('Sum of squared error')
    ax_elbow.plot(k_rng, sse, marker='o', color='purple', linestyle='--')
    ax_elbow.set_title("Elbow Method Evaluation")
    st.pyplot(fig_elbow)

# -------------------------------------------------------------
# 7. Raw Processed Data Overview Element
# -------------------------------------------------------------
st.write("---")
st.subheader("Processed DataFrame Preview")
st.dataframe(df_cluster.head(10), use_container_width=True) 
